# -*- coding: utf-8 -*-
"""handwritten_character_recognition.h5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10ToDPi43eF5bdxQIU_5XHbcKc2KtQsKL
"""

import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.utils import to_categorical

# Load dataset
(X_train, y_train), (X_test, y_test) = mnist.load_data()

# Reshape and normalize
X_train = X_train.reshape(-1, 28, 28, 1) / 255.0
X_test = X_test.reshape(-1, 28, 28, 1) / 255.0

# One-hot encode labels
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

# Build CNN model
model = Sequential([
    Conv2D(32, (3,3), activation='relu', input_shape=(28,28,1)),
    MaxPooling2D((2,2)),
    Conv2D(64, (3,3), activation='relu'),
    MaxPooling2D((2,2)),
    Flatten(),
    Dense(128, activation='relu'),
    Dense(10, activation='softmax')
])

# Compile model
model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

# Train model
model.fit(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

# Evaluate
loss, accuracy = model.evaluate(X_test, y_test)
print("Test Accuracy:", accuracy)

model.save("handwritten_character_model.h5")

import matplotlib.pyplot as plt
import numpy as np

index = 10

plt.imshow(X_test[index].reshape(28,28), cmap='gray')
plt.show()

prediction = model.predict(X_test[index].reshape(1,28,28,1))
print("Predicted Digit:", np.argmax(prediction))

from google.colab import files
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt

# Upload image
uploaded = files.upload()

# Get filename
filename = list(uploaded.keys())[0]

# Open image
img = Image.open(filename).convert('L')

# Resize to MNIST size
img = img.resize((28, 28))

# Show image
plt.imshow(img, cmap='gray')
plt.show()

# Preprocess
img_array = np.array(img)

# Invert colors if needed (MNIST = white digit on black background)
img_array = 255 - img_array

img_array = img_array / 255.0
img_array = img_array.reshape(1, 28, 28, 1)

# Predict
prediction = model.predict(img_array)
print("Predicted Digit:", np.argmax(prediction))
print("Confidence:", np.max(prediction) * 100, "%")

prediction = model.predict(img_array)
print(prediction)
print("Predicted Digit:", np.argmax(prediction))

plt.imshow(img_array.reshape(28,28), cmap='gray')
plt.show()

model.fit(X_train, y_train, epochs=10, validation_data=(X_test, y_test))

from PIL import Image
import numpy as np
import matplotlib.pyplot as plt

img = Image.open(filename).convert('L')

# Convert to numpy array
img_array = np.array(img)

# Find digit area
coords = np.argwhere(img_array < 200)

y_min, x_min = coords.min(axis=0)
y_max, x_max = coords.max(axis=0)

# Crop around digit
img_array = img_array[y_min:y_max+1, x_min:x_max+1]

# Resize
img = Image.fromarray(img_array)
img = img.resize((28,28))

# Invert colors
img_array = 255 - np.array(img)

# Normalize
img_array = img_array / 255.0

# Display what model sees
plt.imshow(img_array, cmap='gray')
plt.show()

# Predict
img_array = img_array.reshape(1,28,28,1)

prediction = model.predict(img_array)
print("Predicted Digit:", np.argmax(prediction))
print("Probabilities:", prediction)

plt.imshow(img_array.reshape(28,28), cmap='gray')
plt.show()

prediction = model.predict(img_array)
print(prediction[0])

for i, p in enumerate(prediction[0]):
    print(f"{i}: {p:.4f}")

from google.colab import files
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt

# Upload image
uploaded = files.upload()

# Get filename
filename = list(uploaded.keys())[0]

# Open image
img = Image.open(filename).convert('L')

# Resize to MNIST size
img = img.resize((28, 28))

# Show image
plt.imshow(img, cmap='gray')
plt.show()

# Preprocess
img_array = np.array(img)

# Invert colors if needed (MNIST = white digit on black background)
img_array = 255 - img_array

img_array = img_array / 255.0
img_array = img_array.reshape(1, 28, 28, 1)

# Predict
prediction = model.predict(img_array)
print("Predicted Digit:", np.argmax(prediction))
print("Confidence:", np.max(prediction) * 100, "%")

from google.colab import files
from PIL import Image, ImageOps
import numpy as np
import matplotlib.pyplot as plt

uploaded = files.upload()
filename = list(uploaded.keys())[0]

# Open image
img = Image.open(filename).convert('L')

# Invert: black digit on white -> white digit on black
img = ImageOps.invert(img)

# Crop digit
img_array = np.array(img)
coords = np.argwhere(img_array > 50)

y_min, x_min = coords.min(axis=0)
y_max, x_max = coords.max(axis=0)

img_array = img_array[y_min:y_max+1, x_min:x_max+1]

# Make square
h, w = img_array.shape
size = max(h, w)

square = np.zeros((size, size), dtype=np.uint8)

y_offset = (size - h) // 2
x_offset = (size - w) // 2

square[y_offset:y_offset+h, x_offset:x_offset+w] = img_array

# Resize to 20x20
img = Image.fromarray(square)
img = img.resize((20, 20))

# Put in center of 28x28 canvas
canvas = np.zeros((28, 28), dtype=np.uint8)
canvas[4:24, 4:24] = np.array(img)

# Show what model sees
plt.imshow(canvas, cmap='gray')
plt.show()

# Predict
canvas = canvas.astype("float32") / 255.0
canvas = canvas.reshape(1, 28, 28, 1)

prediction = model.predict(canvas)

print("Predicted Digit:", np.argmax(prediction))
print("Confidence:", np.max(prediction) * 100)

from google.colab import files
from PIL import Image, ImageOps
import numpy as np
import matplotlib.pyplot as plt

uploaded = files.upload()
filename = list(uploaded.keys())[0]

# Open image
img = Image.open(filename).convert('L')

# Invert: black digit on white -> white digit on black
img = ImageOps.invert(img)

# Crop digit
img_array = np.array(img)
coords = np.argwhere(img_array > 50)

y_min, x_min = coords.min(axis=0)
y_max, x_max = coords.max(axis=0)

img_array = img_array[y_min:y_max+1, x_min:x_max+1]

# Make square
h, w = img_array.shape
size = max(h, w)

square = np.zeros((size, size), dtype=np.uint8)

y_offset = (size - h) // 2
x_offset = (size - w) // 2

square[y_offset:y_offset+h, x_offset:x_offset+w] = img_array

# Resize to 20x20
img = Image.fromarray(square)
img = img.resize((20, 20))

# Put in center of 28x28 canvas
canvas = np.zeros((28, 28), dtype=np.uint8)
canvas[4:24, 4:24] = np.array(img)

# Show what model sees
plt.imshow(canvas, cmap='gray')
plt.show()

# Predict
canvas = canvas.astype("float32") / 255.0
canvas = canvas.reshape(1, 28, 28, 1)

prediction = model.predict(canvas)

print("Predicted Digit:", np.argmax(prediction))
print("Confidence:", np.max(prediction) * 100)

from google.colab import files
from PIL import Image, ImageOps
import numpy as np
import matplotlib.pyplot as plt

uploaded = files.upload()
filename = list(uploaded.keys())[0]

# Open image
img = Image.open(filename).convert('L')

# Invert: black digit on white -> white digit on black
img = ImageOps.invert(img)

# Crop digit
img_array = np.array(img)
coords = np.argwhere(img_array > 50)

y_min, x_min = coords.min(axis=0)
y_max, x_max = coords.max(axis=0)

img_array = img_array[y_min:y_max+1, x_min:x_max+1]

# Make square
h, w = img_array.shape
size = max(h, w)

square = np.zeros((size, size), dtype=np.uint8)

y_offset = (size - h) // 2
x_offset = (size - w) // 2

square[y_offset:y_offset+h, x_offset:x_offset+w] = img_array

# Resize to 20x20
img = Image.fromarray(square)
img = img.resize((20, 20))

# Put in center of 28x28 canvas
canvas = np.zeros((28, 28), dtype=np.uint8)
canvas[4:24, 4:24] = np.array(img)

# Show what model sees
plt.imshow(canvas, cmap='gray')
plt.show()

# Predict
canvas = canvas.astype("float32") / 255.0
canvas = canvas.reshape(1, 28, 28, 1)

prediction = model.predict(canvas)

print("Predicted Digit:", np.argmax(prediction))
print("Confidence:", np.max(prediction) * 100)

model.save("handwritten_character_model.h5")

model.save("handwritten_character_model.keras")